# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: prisma_access_load_config_partial_01_api_v90
# label used for menu selection
label: Configure - Step 2 - Prisma Access Load Config Partial Part 1 for Mobile User Configuration
description: |
  Prisma Access load config partial skillet for Mobile User imported configuration file.
  Mobile User template config to commit for cert gen and optional Service Setup configuration

type: panorama

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  order: 35
  collection:
    - Prisma Access Mobile User

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
variables:

  - name: conf_filename
    description: name of imported file
    default: prisma_access_full_config.xml
    type_hint: text
    help_text: file name used in the load config partial commands
  - name: include_svc_setup
    description: Include initial Service Setup configuration
    default: 'no'
    type_hint: disabled
    help_text: this values is set in the Generate Config skillet when creating the full XML config file

snippets:

  - name: svc_conn_template
    when: include_svc_setup == 'yes'
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='Service_Conn_Template']</from-xpath>
                  <to-xpath>/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='Service_Conn_Template']</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_template_stack
    when: include_svc_setup == 'yes'
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='Service_Conn_Template_Stack']</from-xpath>
                  <to-xpath>/config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='Service_Conn_Template_Stack']</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_device_group
    when: include_svc_setup == 'yes'
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Service_Conn_Device_Group']</from-xpath>
                  <to-xpath>/config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Service_Conn_Device_Group']</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_onboarding
    when: include_svc_setup == 'yes'
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/service-connection</from-xpath>
                  <to-xpath>/config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/service-connection</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: mobile_user_template
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='Mobile_User_Template']</from-xpath>
                  <to-xpath>/config/devices/entry[@name='localhost.localdomain']/template/entry[@name='Mobile_User_Template']</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

# ---------------------------------------------------------------------
# end of snippets section